name: Build APK

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: 22

      - uses: oven-sh/setup-bun@v2

      - name: install and prebuild
        run: |
          bun link
          bun install --frozen-lockfile
          bun bundle:es
          
          # Đổi Package ID để cài song song, không đè app cũ
          sed -i 's/jp.nonbili.noutube/jp.nonbili.noutube.mod/' app.config.ts
          # Đổi tên hiển thị trên màn hình thành NouTube Mod
          sed -i 's/NouTube/NouTube Mod/' app.config.ts
          
          bun expo prebuild -p android --clean --no-install

      - name: build apk
        run: |
          # Chèn chữ ký debug vào bản release để bỏ qua lỗi đòi mật khẩu bảo mật
          sed -i '/release {/a \            signingConfig signingConfigs.debug' app/build.gradle
          ./gradlew assembleFullRelease
        working-directory: android

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NouTube-Mod-Release
          path: android/app/build/outputs/apk/full/release/*-release.apk
